sources:
  - name: arbitrum
    handler:
      graphql:
        endpoint: https://gateway-arbitrum.network.thegraph.com/api/cfd41a9b70fcff12512d9fafecc0387d/subgraphs/id/eVibF32AJuoYG4DorvFTrJ6hH7ZxZdpMj1Jg6iAfbHb

    transforms:
      - prefix:
          mode: wrap
          value: "c42161_"
          includeRootOperations: true
          includeTypes: false

  - name: linea
    handler:
      graphql:
        endpoint: https://graph-query.linea.build/subgraphs/name/LedgityLabs/LedgityYield
    transforms:
      - prefix:
          mode: wrap
          value: "c59144_"
          includeRootOperations: true
          includeTypes: false

  - name: OKX_X1_Testnet
    handler:
      graphql:
        endpoint: https://www.okx.com/api/v1/x1-testnet/index/subgraphs/name/LedgityLabs/LedgityYield
    transforms:
      - prefix:
          mode: wrap
          value: "c195_"
          includeRootOperations: true
          includeTypes: false

  # - name: localhost
  #   handler:
  #     graphql:
  #       endpoint: http://0.0.0.0:8000/subgraphs/name/LedgityLabs/LedgityYield
  #   transforms:
  #     - prefix:
  #         mode: wrap
  #         value: "c31337_"
  #         includeRootOperations: true
  #         includeTypes: false
