sources:
  - name: arbitrum
    handler:
      graphql:
        endpoint: https://subgraph.satsuma-prod.com/8a26f33a279b/ledgity--128781/ledgity-subgraph/api

    transforms:
      - prefix:
          mode: wrap
          value: "c42161_"
          includeRootOperations: true
          includeTypes: false

  - name: linea
    handler:
      graphql:
        endpoint: https://subgraph.satsuma-prod.com/8a26f33a279b/ledgity--128781/ledgity-linea/api
    transforms:
      - prefix:
          mode: wrap
          value: "c59144_"
          includeRootOperations: true
          includeTypes: false

  - name: ethereum
    handler:
      graphql:
        endpoint: https://subgraph.satsuma-prod.com/8a26f33a279b/ledgity--128781/eth-vault/api
    transforms:
      - prefix:
          mode: wrap
          value: "c1_"
          includeRootOperations: true
          includeTypes: false

  - name: base
    handler:
      graphql:
        endpoint: https://subgraph.satsuma-prod.com/8a26f33a279b/ledgity--128781/ledgity-yield-base/api
    transforms:
      - prefix:
          mode: wrap
          value: "c8453_"
          includeRootOperations: true
          includeTypes: false
