[profile.default]
src = "contracts/src"
out = "contracts/foundry/out"
libs = ["node_modules", "contracts/foundry/lib"]
cache_path = "contracts/foundry/cache"
test = "contracts/foundry/test"
optimizer = true
optimizer_runs = 200
evm_version = "london"

[profile.default.fuzz]
runs = 10000

[profile.default.invariant]
runs = 10000
depth = 50

[profile.ci.fuzz]
runs = 10000

[profile.ci.invariant]
runs = 10000
depth = 50