import {
  injectedWallet,
  rainbowWallet,
  walletConnectWallet,
  argentWallet,
  bitskiWallet,
  braveWallet,
  coinbaseWallet,
  dawnWallet,
  ledgerWallet,
  imTokenWallet,
  metaMaskWallet,
  okxWallet,
  omniWallet,
  phantomWallet,
  rabbyWallet,
  safeWallet,
  tahoWallet,
  trustWallet,
  xdefiWallet,
  zerionWallet,
} from "@rainbow-me/rainbowkit/wallets";

export const wallets = [
  {
    groupName: "Popular",
    wallets: [
      metaMaskWallet,
      rainbowWallet,
      safeWallet,
      ledgerWallet,
      trustWallet,
      okxWallet,
      phantomWallet,
      coinbaseWallet,
      braveWallet,
      argentWallet,
      walletConnectWallet,
      injectedWallet,
    ],
  },
  {
    groupName: "Others",
    wallets: [
      bitskiWallet,
      dawnWallet,
      imTokenWallet,
      omniWallet,
      rabbyWallet,
      tahoWallet,
      xdefiWallet,
      zerionWallet,
    ],
  },
];
